"""DTO definitions bridging domain entities and transport layers."""

from .admin import (
    AdminGlobalKeyDTO,
    AdminRoleDTO,
    AdminUserDTO,
    admin_global_key_to_dto,
    admin_global_keys_to_dto,
    admin_role_to_dto,
    admin_roles_to_dto,
    admin_user_to_dto,
    admin_users_to_dto,
)
from .base import DomainModel
from .chat import (
    ChatMessageDTO,
    ChatSessionDTO,
    chat_message_to_dto,
    chat_messages_to_dto,
    chat_session_to_dto,
    chat_sessions_to_dto,
)
from .settings import AdminEnvResponseDTO, BackupInfoDTO, EnvSettingDTO
from .suggestions import (
    SuggestionCommentDTO,
    SuggestionCommentResponseDTO,
    SuggestionDTO,
    SuggestionItemDTO,
    SuggestionListDTO,
    SuggestionMetaDTO,
    meta_to_dto,
    suggestion_to_dto,
    suggestions_to_dto,
)
from .users import (
    GlobalAPIKeyDTO,
    UserAPIKeyDTO,
    UserDTO,
    global_key_to_dto,
    user_key_to_dto,
    user_keys_to_dto,
    user_to_dto,
    users_to_dto,
)
from .vcenter import (
    VCenterConfigDTO,
    VCenterVMDTO,
    vcenter_config_to_dto,
    vcenter_configs_to_dto,
    vcenter_vm_to_dto,
    vcenter_vms_to_dto,
)

__all__ = [
    "AdminEnvResponseDTO",
    "AdminGlobalKeyDTO",
    "AdminRoleDTO",
    "AdminUserDTO",
    "BackupInfoDTO",
    "ChatMessageDTO",
    "ChatSessionDTO",
    "DomainModel",
    "EnvSettingDTO",
    "GlobalAPIKeyDTO",
    "SuggestionCommentDTO",
    "SuggestionCommentResponseDTO",
    "SuggestionDTO",
    "SuggestionItemDTO",
    "SuggestionListDTO",
    "SuggestionMetaDTO",
    "UserAPIKeyDTO",
    "UserDTO",
    "VCenterConfigDTO",
    "VCenterVMDTO",
    "admin_global_key_to_dto",
    "admin_global_keys_to_dto",
    "admin_role_to_dto",
    "admin_roles_to_dto",
    "admin_user_to_dto",
    "admin_users_to_dto",
    "chat_message_to_dto",
    "chat_messages_to_dto",
    "chat_session_to_dto",
    "chat_sessions_to_dto",
    "global_key_to_dto",
    "meta_to_dto",
    "suggestion_to_dto",
    "suggestions_to_dto",
    "user_key_to_dto",
    "user_keys_to_dto",
    "user_to_dto",
    "users_to_dto",
    "vcenter_config_to_dto",
    "vcenter_configs_to_dto",
    "vcenter_vm_to_dto",
    "vcenter_vms_to_dto",
]
